### ISSUE TITLE
Problems running BEAST with the XML

### ISSUE THREAD

**Issue by Marialejandra** [Taming-the-BEAST/Prior-selection#2]
Hola! I'm trying to do this tutorial , but I'm having problems with BEAST. When a try to run the xml file with the setting ready BEAST give me this error:

Start likelihood: -Infinity after 10 initialisation attempts
P(posterior) = -Infinity (was -Infinity)
P(prior) = -Infinity (was -Infinity)
P(BirthDeathSkySerial.t:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -Infinity (was -Infinity)
P(ClockPrior.c:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -20.060738782187734 (was -20.060738782187734)
P(GammaShapePrior.s:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -1.0 (was -1.0)
P(KappaPrior.s:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -1.8653600339742873 (was -1.8653600339742873)
P(samplingProportionPrior.t:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -Infinity (was -Infinity)
P(originPrior.t:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -53.22152362619872 (was -53.22152362619872)
P(becomeUninfectiousRatePrior.t:InfluenzaAH3N2_HAgene_2009_California_heterochronous) = -1.4620820845188824 (was -1.4620820845188824)

P(reproductiveNumberPrior.t:InfluenzaAH3N2_HAgene_2009_California_java.lang.RuntimeException: 
Could not find a proper state to initialise. Perhaps try another seed.
at beast.core.MCMC.run(Unknown Source)
at beast.app.BeastMCMC.run(Unknown Source)
at beast.app.beastapp.BeastMain.<init>(Unknown Source)
at beast.app.beastapp.BeastMain.main(Unknown Source)
at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Could not find a proper state to initialise. Perhaps try another seed.
heterochronous) = -9.261561103618593 (was -9.261561103618593)
P(likelihood) = NaN (was NaN)  **
P(treeLikelihood.InfluenzaAH3N2_HAgene_2009_California_heterochronous) = NaN (was NaN)  **
Fatal exception: Could not find a proper state to initialise. Perhaps try another seed.

When I try with yours xml file (heterochronous.xml) the results is this error:

Warning: Overwriting file C:\Users\Negrita\Desktop\Tutoriales BEAST\Prior-selection-master\xml/InfluenzaAH3N2_HAgene_2009_California_heterochronous.log

Start likelihood: -13637.083782317275 

Warning: Overwriting file C:\Users\Negrita\Desktop\Tutoriales BEAST\Prior-selection-master\xml/InfluenzaAH3N2_HAgene_2009_California_heterochronous.trees

  Sample      posterior ESS(posterior)     likelihood          prior
  0    -13637.0837              N    -12916.5926      -720.4911 --
 1000     -8160.8566         2.0        -8141.8331       -19.0235 --
 2000     -7037.9066         3.0        -7125.5770        87.6703 --
Fatal exception: null
java.lang.NullPointerException
at beast.evolution.speciation.BirthDeathSkylineModel.calculateTreeLogLikelihood(Unknown Source)
at beast.evolution.speciation.SpeciesTreeDistribution.calculateLogP(Unknown Source)
at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
at beast.core.MCMC.propagateState(Unknown Source)
at beast.core.MCMC.doLoop(Unknown Source)
at beast.core.MCMC.run(Unknown Source)
at beast.app.BeastMCMC.run(Unknown Source)
at beast.app.beastapp.BeastMain.<init>(Unknown Source)
at beast.app.beastapp.BeastMain.main(Unknown Source)
at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: null

Can you help me with this problems? Thank you guys!

**Comment by laduplessis** [comment]
Hi Maria, 

It looks like there is an issue with the sampling proportion prior in your xml file. Please check that you set the right upper and lower limits (0 and 1) and set the same prior as in the tutorial. Please also make sure that you selected "Birth Death Skyline Serial" as the tree model.  

I tried the xml on the repository and it worked without any problems. I used Beast v2.4.7, BDSKY v1.3.3 and used a seed of 127. Could you please try it with the same version of Beast2 and the same seed? 

Best regards,
Louis

**Comment by Marialejandra** [comment]
Hola Louis! I’m sorry for answering so late. I was fixing my computer. I’m starting again with the tutorials and I’m having the same problem. I downloaded de last versión of BEAST (v 2.5.0) with JAVA and the BDSKY versión that I have is 1.4.0 . I tried the seed 127 and this is what I got: 

Start likelihood: -14561.96576200475 
Writing file C:\Users\Negrita\Desktop\Tutoriales BEAST\Prior-selection-master\Resultados\InfluenzaAH3N2_HAgene_2009_California_heterochronous.log
Writing file C:\Users\Negrita\Desktop\Tutoriales BEAST\Prior-selection-master\Resultados\InfluenzaAH3N2_HAgene_2009_California_heterochronous.trees
         Sample      posterior ESS(posterior)     likelihood          prior
              0    -14549.3797              N    -13826.6952      -722.6845 --
           1000     -8836.2449         2.0        -8816.2233       -20.0216 --
java.lang.NullPointerException
	at beast.evolution.speciation.BirthDeathSkylineModel.calculateTreeLogLikelihood(Unknown Source)
	at beast.evolution.speciation.SpeciesTreeDistribution.calculateLogP(Unknown Source)
	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.core.MCMC.propagateState(Unknown Source)
	at beast.core.MCMC.doLoop(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
Fatal exception: null
Fatal exception: null
BEAST has terminated with an error. Please select QUIT from the menu.

I try again with your XML and I get a similir error. 

Thank you for your help!!

**Comment by Marialejandra** [comment]
Hola Louis! I’m sorry for answering so late. I was fixing my computer. I’m starting again with the tutorials and I’m having the same problem. I downloaded de last versión of BEAST (v 2.5.0) with JAVA and the BDSKY versión that I have is 1.4.0 . I tried the seed 127 and this is what I got: 

Start likelihood: -14561.96576200475 
Writing file C:\Users\Negrita\Desktop\Tutoriales BEAST\Prior-selection-master\Resultados\InfluenzaAH3N2_HAgene_2009_California_heterochronous.log
Writing file C:\Users\Negrita\Desktop\Tutoriales BEAST\Prior-selection-master\Resultados\InfluenzaAH3N2_HAgene_2009_California_heterochronous.trees
         Sample      posterior ESS(posterior)     likelihood          prior
              0    -14549.3797              N    -13826.6952      -722.6845 --
           1000     -8836.2449         2.0        -8816.2233       -20.0216 --
java.lang.NullPointerException
	at beast.evolution.speciation.BirthDeathSkylineModel.calculateTreeLogLikelihood(Unknown Source)
	at beast.evolution.speciation.SpeciesTreeDistribution.calculateLogP(Unknown Source)
	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.core.MCMC.propagateState(Unknown Source)
	at beast.core.MCMC.doLoop(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
Fatal exception: null
Fatal exception: null
BEAST has terminated with an error. Please select QUIT from the menu.

I try again with your XML and I get a similir error. 

Thank you for your help!!

**Comment by laduplessis** [comment]
Hi Maria, it is not immediately obvious to me what the problem is. Could you please attach your XML file so I can try to find the issue? 

Best regards,
Louis

**Comment by Marialejandra** [comment]
Ok Louis. This is the file that I used. I created the file following the
instructions in the tutorial.

2018-05-08 10:16 GMT-04:00 Louis <notifications@github.com>:

**Comment by laduplessis** [comment]
Please zip the xml file and then drag and drop it into the comment box.

**Comment by Marialejandra** [comment]
Sorry Louis... This is the file. 
[heterochronous.zip](https://github.com/Taming-the-BEAST/Prior-selection/files/1988423/heterochronous.zip)

**Comment by laduplessis** [comment]
Hi Maria, 

I had no issues running your xml file in Beast 2.4.7 or Beast 2.5.0 (I used MacOS Sierra and I have Beagle installed). Thus, the problem appears to be with Beast2 and not with your xml file. Does Beast2 only crash with this xml file, with all xml files or only with xml files that use the birth-death skyline? If you have access to any other machines I would also suggest trying to run the xml file on them.

**Comment by Marialejandra** [comment]
Thank you Louis! I will try with another computer and with others xml files from others tutorials that I'm doing. I will let you know the results.

**Comment by zyy-1111** [comment]
xml.state can't be made. Could you have some advice?
![image](https://github.com/Taming-the-BEAST/Prior-selection/assets/81152546/4387daf4-bc28-4190-9e00-8ea0194f84ee)

**Comment by laduplessis** [comment]
You might not have write permissions, or perhaps the file exists with permissions that are not allowing BEAST2 to overwrite it. Otherwise, try moving the xml file somewhere else and running it there.

This is not an issue with the tutorial, but either with your machine setup or (less likely) BEAST2 itself.
